/**
 * Form interception utilities.
 *
 * This module contains the logic that gets serialised into a self-contained
 * <script> block and injected into published pages via the renderer.
 *
 * The IIFE generated by `buildInterceptionScript()` performs the following:
 *   1. Finds forms on the page matching CSS selectors from stored bindings
 *   2. Prevents default submit
 *   3. Extracts all field values (including hidden fields)
 *   4. Maps values through the stored field mapping → canonical payload
 *   5. Captures UTMs from cookie / localStorage
 *   6. POSTs to /api/v1/submissions/submit
 *   7. Handles success (inline message, redirect, or modal)
 *   8. Handles errors gracefully
 */

/* ── Types (mirrored from API for documentation; not emitted at runtime) ── */

export interface FormBinding {
  selector: string;
  fieldMappings: Record<string, string>; // formFieldName → canonical key
}

export interface SuccessConfig {
  behavior: 'inline' | 'redirect' | 'modal';
  redirectUrl?: string;
  message?: string;
}

export interface InterceptionScriptParams {
  pageId: string;
  pageName: string;
  pageSlug: string;
  bindings: FormBinding[];
  success: SuccessConfig;
}

/* ── UTM helpers (plain JS, will be inlined) ── */

const UTM_STORAGE_KEY = 'replica_utm';
const UTM_COOKIE_NAME = 'replica_utm';

/**
 * Build the body of the self-contained IIFE that gets injected into the page.
 *
 * Kept as a plain string so it can be emitted verbatim by the renderer
 * without any bundler involvement.
 */
export function buildInterceptionIIFE(params: InterceptionScriptParams): string {
  const bindingsJson = JSON.stringify(params.bindings);
  const successJson = JSON.stringify(params.success);
  const pageId = jsonEscape(params.pageId);
  const pageName = jsonEscape(params.pageName);
  const pageSlug = jsonEscape(params.pageSlug);

  // The IIFE below is plain ES5-compatible JS for maximum browser compat.
  return `(function(){
"use strict";
var BINDINGS=${bindingsJson};
var SUCCESS=${successJson};
var PAGE_ID="${pageId}";
var PAGE_NAME="${pageName}";
var PAGE_SLUG="${pageSlug}";
var SUBMIT_URL="/api/v1/submissions/submit";

${getUtmReaderSnippet()}
${getFormMatcherSnippet()}
${getPayloadBuilderSnippet()}
${getSubmitHandlerSnippet()}
${getSuccessHandlerSnippet()}

init();
})();`;
}

/* ── Internal snippets (each returns a JS string) ── */

function getUtmReaderSnippet(): string {
  return `
function getUtm(){
  try{
    var s=localStorage.getItem("${UTM_STORAGE_KEY}");
    if(s)return JSON.parse(s);
  }catch(e){}
  var m=document.cookie.match(new RegExp("(?:^|;)\\\\s*${UTM_COOKIE_NAME}\\\\s*=\\\\s*([^;]*)"));
  if(m){try{return JSON.parse(decodeURIComponent(m[1]));}catch(e){}}
  return {};
}`;
}

function getFormMatcherSnippet(): string {
  return `
function init(){
  BINDINGS.forEach(function(b){
    var forms=document.querySelectorAll(b.selector);
    forms.forEach(function(form){
      if(form.__rp_hooked)return;
      form.__rp_hooked=true;
      form.addEventListener("submit",function(ev){
        ev.preventDefault();
        handleSubmit(form,b);
      });
    });
  });
}`;
}

function getPayloadBuilderSnippet(): string {
  return `
function buildPayload(form,binding){
  var fd=new FormData(form);
  var mapped={};
  var custom={};
  var entries=binding.fieldMappings||{};
  for(var name in entries){
    var canonical=entries[name];
    var val=fd.get(name);
    if(val==null)val="";
    val=String(val);
    if(canonical.indexOf("custom:")===0){
      custom[canonical.slice(7)]=val;
    }else{
      mapped[canonical]=val;
    }
  }
  var utm=getUtm();
  var payload={
    page_id:PAGE_ID,
    page_name:PAGE_NAME,
    page_slug:PAGE_SLUG,
    page_url:window.location.href,
    utm_page:PAGE_NAME||PAGE_SLUG,
    utm_source:utm.utm_source||"",
    utm_medium:utm.utm_medium||"",
    utm_campaign:utm.utm_campaign||"",
    utm_term:utm.utm_term||"",
    utm_content:utm.utm_content||"",
    referrer:document.referrer||"",
    landing_url:window.location.href,
    timestamp:new Date().toISOString(),
    user_agent:navigator.userAgent||""
  };
  for(var k in mapped){payload[k]=mapped[k];}
  if(Object.keys(custom).length>0)payload.custom_fields=custom;
  return payload;
}`;
}

function getSubmitHandlerSnippet(): string {
  return `
function handleSubmit(form,binding){
  var payload=buildPayload(form,binding);
  var btn=form.querySelector("[type=submit]");
  if(btn){btn.disabled=true;btn.textContent="Submitting...";}
  fetch(SUBMIT_URL,{
    method:"POST",
    headers:{"Content-Type":"application/json"},
    body:JSON.stringify(payload),
    credentials:"same-origin"
  })
  .then(function(r){return r.json().then(function(d){return{ok:r.ok,data:d};});})
  .then(function(res){
    if(res.ok&&res.data.success){
      handleSuccess(form);
    }else{
      handleError(form,res.data.error||"Submission failed");
    }
  })
  .catch(function(){
    handleError(form,"Network error. Please try again.");
  });
}`;
}

function getSuccessHandlerSnippet(): string {
  return `
function handleSuccess(form){
  var msg=SUCCESS.message||"Thanks for submitting!";
  if(SUCCESS.behavior==="redirect"&&SUCCESS.redirectUrl){
    window.location.href=SUCCESS.redirectUrl;
    return;
  }
  if(SUCCESS.behavior==="modal"){
    showModal(msg);
    form.reset();
    var btn=form.querySelector("[type=submit]");
    if(btn){btn.disabled=false;btn.textContent="Submit";}
    return;
  }
  form.innerHTML='<div style="padding:12px;color:#16a34a;font-weight:500">'+escText(msg)+"</div>";
}
function showModal(msg){
  var overlay=document.createElement("div");
  overlay.style.cssText="position:fixed;inset:0;z-index:99999;background:rgba(0,0,0,0.5);display:flex;align-items:center;justify-content:center";
  var box=document.createElement("div");
  box.style.cssText="background:#fff;border-radius:8px;padding:24px 32px;max-width:400px;text-align:center";
  box.innerHTML='<p style="font-size:1rem;margin:0 0 16px">'+escText(msg)+'</p><button style="padding:6px 20px;border:1px solid #ccc;border-radius:4px;cursor:pointer">Close</button>';
  box.querySelector("button").addEventListener("click",function(){document.body.removeChild(overlay);});
  overlay.appendChild(box);
  document.body.appendChild(overlay);
}
function handleError(form,msg){
  var btn=form.querySelector("[type=submit]");
  if(btn){btn.disabled=false;btn.textContent="Submit";}
  var el=form.querySelector(".rp-form-error");
  if(!el){el=document.createElement("div");el.className="rp-form-error";el.style.cssText="color:#dc2626;font-size:0.875rem;margin-top:8px";form.appendChild(el);}
  el.textContent=msg;
}
function escText(s){return s.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");}`;
}

/* ── Helpers ── */

/** Escape a string for safe embedding inside a JSON/JS double-quoted string */
function jsonEscape(s: string): string {
  return s
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r');
}
